---
  extends:
    - airbnb
    - plugin:jest/recommended
    - plugin:react/recommended

  parser: babel-eslint

  plugins:
  - jest
  - babel

  env:
    node: true
    jest/globals: true
    browser: true

  rules:
    react/prop-types: 0
    no-console: 0
